# Para descargar y levantar el archivo

# Preguntas

Que hago si el dataset tiene columnas sin nombre? hubo un problema con comas de mas.

El ultimo dataset xlsx tambien tiene el mismo problema

# Ej 2

In [2]:
# instalamos el paquete para descargar archivos wget
#!pip install wget

from wget import download
from os import path, listdir


# descargamos la descripcion en TXT
if not path.exists("netflix_titles.txt"):
  download("https://ignaciorlando.github.io/datasets/data-science/netflix_titles.txt")
else:
  print("No vamos a bajar la descripcion porque ya existe!")

# descargamos una base de datos en CSV
if not path.exists("netflix_titles.csv"):
  download("https://ignaciorlando.github.io/datasets/data-science/netflix_titles.csv")
else:
  print("No vamos a bajar el archivo porque ya existe!")

# chequeamos si los archivos están en el directorio donde estamos parados
lista_archivos = listdir("./")
print(f"El contenido de la carpeta es: {lista_archivos}")

No vamos a bajar la descripcion porque ya existe!
No vamos a bajar el archivo porque ya existe!
El contenido de la carpeta es: ['ej2.ipynb', 'netflix_titles.csv', 'netflix_titles.txt', 'tp2.ipynb', 'amb-ej2']

In [ ]:
import pandas as pd

# abrimos el archivo usando una función específica de pandas
raw_dataset = pd.read_csv("netflix_titles.csv", encoding='utf-8')

In [ ]:

raw_dataset.info()
raw_dataset.head()

<class 'pandas.DataFrame'>
RangeIndex: 8809 entries, 0 to 8808
Data columns (total 26 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8809 non-null   str
 1   type          8809 non-null   str
 2   title         8809 non-null   str
 3   director      6175 non-null   str
 4   cast          7984 non-null   str
 5   country       7978 non-null   str
 6   date_added    8799 non-null   str
 7   release_year  8809 non-null   int64
 8   rating        8805 non-null   str
 9   duration      8806 non-null   str
 10  listed_in     8809 non-null   str
 11  description   8809 non-null   str
 12  Unnamed: 12   0 non-null      float64
 13  Unnamed: 13   0 non-null      float64
 14  Unnamed: 14   0 non-null      float64
 15  Unnamed: 15   0 non-null      float64
 16  Unnamed: 16   0 non-null      float64
 17  Unnamed: 17   0 non-null      float64
 18  Unnamed: 18   0 non-null      float64
 19  Unnamed: 19   0 non-null      float64
 20  Unnamed: 20   0 non-null      float64
 21  Unnamed: 21   0 non-null      float64
 22  Unnamed: 22   0 non-null      float64
 23  Unnamed: 23   0 non-null      float64
 24  Unnamed: 24   0 non-null      float64
 25  Unnamed: 25   0 non-null      float64
dtypes: float64(14), int64(1), str(11)
memory usage: 1.7 MB

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,...,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
raw_dataset.info()

<class 'pandas.DataFrame'>
RangeIndex: 8809 entries, 0 to 8808
Data columns (total 26 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8809 non-null   str
 1   type          8809 non-null   str
 2   title         8809 non-null   str
 3   director      6175 non-null   str
 4   cast          7984 non-null   str
 5   country       7978 non-null   str
 6   date_added    8799 non-null   str
 7   release_year  8809 non-null   int64
 8   rating        8805 non-null   str
 9   duration      8806 non-null   str
 10  listed_in     8809 non-null   str
 11  description   8809 non-null   str
 12  Unnamed: 12   0 non-null      float64
 13  Unnamed: 13   0 non-null      float64
 14  Unnamed: 14   0 non-null      float64
 15  Unnamed: 15   0 non-null      float64
 16  Unnamed: 16   0 non-null      float64
 17  Unnamed: 17   0 non-null      float64
 18  Unnamed: 18   0 non-null      float64
 19  Unnamed: 19   0 non-null      float64
 20  Unnamed: 20   0 non-null      float64
 21  Unnamed: 21   0 non-null      float64
 22  Unnamed: 22   0 non-null      float64
 23  Unnamed: 23   0 non-null      float64
 24  Unnamed: 24   0 non-null      float64
 25  Unnamed: 25   0 non-null      float64
dtypes: float64(14), int64(1), str(11)
memory usage: 1.7 MB

In [7]:
# Contamos la cantidad de directores según cada valor único de RAD
cant_dir = raw_dataset['director'].nunique()

# Mostramos los resultados
print(f"Hay {cant_dir} directores en el dataset")

Hay 4529 directores en el dataset

In [8]:
#Director con mas peliculas

# filtramos el DataFrame para obtener los registros de MOVIES
registros_peliculas = raw_dataset[raw_dataset["type"] == "Movie"]

cant_peliculas = registros_peliculas.shape[0]

mayor_director = registros_peliculas.value_counts("director").sort_values(ascending=False).head(1)

print(f"{mayor_director} es el director con más películas en el dataset")

director
Rajiv Chilaka    19
Name: count, dtype: int64 es el director con más películas en el dataset

In [9]:
registros_serires = raw_dataset[raw_dataset["type"] == "TV Show"]

cant_registros = registros_serires.shape[0]

print(f"Hay {cant_registros} series")

Hay 2677 series

In [ ]:
peliculas_viejas = registros_peliculas.sort_values(by="release_year",ascending=1)

peliculas_viejas.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,...,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25
7790,s7791,Movie,Prelude to War,Frank Capra,NaN,United States,"March 31, 2017",1942,TV-14,52 min,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8205,s8206,Movie,The Battle of Midway,John Ford,"Henry Fonda, Jane Darwell",United States,"March 31, 2017",1942,TV-14,18 min,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8660,s8661,Movie,Undercover: How to Operate Behind Enemy Lines,John Ford,NaN,United States,"March 31, 2017",1943,TV-PG,61 min,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8739,s8740,Movie,Why We Fight: The Battle of Russia,"Frank Capra, Anatole Litvak",NaN,United States,"March 31, 2017",1943,TV-PG,82 min,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8763,s8764,Movie,WWII: Report from the Aleutians,John Huston,NaN,United States,"March 31, 2017",1943,TV-PG,45 min,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [18]:
peliculas_viejas = registros_serires.sort_values(by="release_year", ascending=1)

peliculas_viejas.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,...,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25
4250,s4251,TV Show,Pioneers: First Women Filmmakers*,NaN,NaN,NaN,"December 30, 2018",1925,TV-14,1 Season,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1331,s1332,TV Show,Five Came Back: The Reference Films,NaN,NaN,United States,"February 9, 2021",1945,TV-MA,1 Season,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7743,s7744,TV Show,Pioneers of African-American Cinema,"Oscar Micheaux, Spencer Williams, Richard E. N...",NaN,United States,"February 1, 2017",1946,TV-14,1 Season,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8541,s8542,TV Show,The Twilight Zone (Original Series),NaN,Rod Serling,United States,"July 1, 2017",1963,TV-14,4 Seasons,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8189,s8190,TV Show,The Andy Griffith Show,NaN,"Andy Griffith, Ron Howard, Don Knotts, Frances...",United States,"July 1, 2017",1967,TV-G,8 Seasons,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [21]:
pais_deseado = input("Ingrese un pais que quiera conocer")

peliculas_pais = registros_peliculas[registros_peliculas["country"] == pais_deseado]

cantidad = peliculas_pais.shape[0]

print(f"{pais_deseado} tiene {cantidad} peliculas")

United States tiene 2059 peliculas

# Ej 3

In [ ]:
# descargamos una base de datos en CSV
if not path.exists("catalogo_streaming_argentina_2024.xlsx"):
  download("https://ignaciorlando.github.io/datasets/data-science/catalogo_streaming_argentina_2024.xlsx")
else:
  print("No vamos a bajar el archivo porque ya existe!")

lista_archivos = listdir("./")
print(f"El contenido de la carpeta es: {lista_archivos}")

No vamos a bajar el archivo porque ya existe!
El contenido de la carpeta es: ['ej2.ipynb', 'netflix_titles.csv', 'netflix_titles.txt', 'tp2.ipynb', 'amb-ej2', 'catalogo_streaming_argentina_2024.xlsx']

In [35]:
#!pip install openpyxl
# abrimos el archivo usando una función específica de pandas
raw_dataset = pd.read_excel("catalogo_streaming_argentina_2024.xlsx")

raw_dataset.info()
raw_dataset.head()

<class 'pandas.DataFrame'>
RangeIndex: 19817 entries, 0 to 19816
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   title           19817 non-null  object
 1   platform        19817 non-null  str
 2   type            19817 non-null  str
 3   imdbVotes       17854 non-null  float64
 4   imdbScore       17927 non-null  float64
 5   tmdbPopularity  19538 non-null  float64
 6   tmdbScore       18954 non-null  float64
 7   runtime         19817 non-null  int64
 8   genres          19665 non-null  str
 9   director        14626 non-null  str
 10  year_range      19817 non-null  object
 11  url             19817 non-null  str
dtypes: float64(4), int64(1), object(2), str(5)
memory usage: 1.8+ MB

,title,platform,type,imdbVotes,imdbScore,tmdbPopularity,tmdbScore,runtime,genres,director,year_range,url
0,Cadena perpetua,Max,MOVIE,2906253.0,9.3,159.594,8.705,142,"Drama, Crimen",Frank Darabont,1900_2002,https://play.max.com/movie/9b4dacba-2f80-4272-...
1,El caballero oscuro,Max,MOVIE,2893241.0,9.0,111.674,8.516,152,"Misterio & Suspense, Drama, Acción & Aventura,...",Christopher Nolan,2003_2010,https://play.max.com/movie/52217243-a137-45d6-...
2,Origen,Max,MOVIE,2570263.0,8.8,139.644,8.369,148,"Ciencia ficción, Acción & Aventura, Misterio &...",Christopher Nolan,2003_2010,https://play.max.com/movie/14552c93-d318-4563-...
3,El club de la lucha,Disney Plus,MOVIE,2345071.0,8.8,108.297,8.400,139,Drama,David Fincher,1998_2004,https://disneyplus.bn5x.net/c/1206980/705874/9...
4,El club de la lucha,Netflix,MOVIE,2345071.0,8.8,108.297,8.400,139,Drama,David Fincher,1995_2005,http://www.netflix.com/title/26004747

In [36]:
raw_dataset.describe()

          imdbVotes     imdbScore  tmdbPopularity     tmdbScore       runtime
count  1.785400e+04  17927.000000    19538.000000  18954.000000  19817.000000
mean   4.838858e+04      6.399520       41.195589      6.461363     80.542867
std    1.488473e+05      1.200258      131.031366      1.254487     37.092943
min    5.000000e+00      1.100000        0.001000      0.500000      0.000000
25%    4.620000e+02      5.700000        5.433250      5.889500     48.000000
50%    2.849500e+03      6.500000       14.428500      6.600000     89.000000
75%    2.196975e+04      7.300000       33.312500      7.273750    105.000000
max    2.906253e+06      9.700000     4173.518000     10.000000    263.000000